export const STATES = [
  { name: 'Alabama', country: 'US', code: 'AL' },
  { name: 'Alaska', country: 'US', code: 'AK' },
  { name: 'Arizona', country: 'US', code: 'AZ' },
  { name: 'Arkansas', country: 'US', code: 'AR' },
  { name: 'California', country: 'US', code: 'CA' },
  { name: 'Colorado', country: 'US', code: 'CO' },
  { name: 'Connecticut', country: 'US', code: 'CT' },
  { name: 'Delaware', country: 'US', code: 'DE' },
  { name: 'District of Columbia', country: 'US', code: 'DC' },
  { name: 'Florida', country: 'US', code: 'FL' },
  { name: 'Georgia', country: 'US', code: 'GA' },
  { name: 'Hawaii', country: 'US', code: 'HI' },
  { name: 'Idaho', country: 'US', code: 'ID' },
  { name: 'Illinois', country: 'US', code: 'IL' },
  { name: 'Indiana', country: 'US', code: 'IN' },
  { name: 'Iowa', country: 'US', code: 'IA' },
  { name: 'Kansas', country: 'US', code: 'KS' },
  { name: 'Kentucky', country: 'US', code: 'KY' },
  { name: 'Louisiana', country: 'US', code: 'LA' },
  { name: 'Maine', country: 'US', code: 'ME' },
  { name: 'Maryland', country: 'US', code: 'MD' },
  { name: 'Massachusetts', country: 'US', code: 'MA' },
  { name: 'Michigan', country: 'US', code: 'MI' },
  { name: 'Minnesota', country: 'US', code: 'MN' },
  { name: 'Mississippi', country: 'US', code: 'MS' },
  { name: 'Missouri', country: 'US', code: 'MO' },
  { name: 'Montana', country: 'US', code: 'MT' },
  { name: 'Nebraska', country: 'US', code: 'NE' },
  { name: 'Nevada', country: 'US', code: 'NV' },
  { name: 'New Hampshire', country: 'US', code: 'NH' },
  { name: 'New Jersey', country: 'US', code: 'NJ' },
  { name: 'New Mexico', country: 'US', code: 'NM' },
  { name: 'New York', country: 'US', code: 'NY' },
  { name: 'North Carolina', country: 'US', code: 'NC' },
  { name: 'North Dakota', country: 'US', code: 'ND' },
  { name: 'Ohio', country: 'US', code: 'OH' },
  { name: 'Oklahoma', country: 'US', code: 'OK' },
  { name: 'Oregon', country: 'US', code: 'OR' },
  { name: 'Pennsylvania', country: 'US', code: 'PA' },
  { name: 'Rhode Island', country: 'US', code: 'RI' },
  { name: 'South Carolina', country: 'US', code: 'SC' },
  { name: 'South Dakota', country: 'US', code: 'SD' },
  { name: 'Tennessee', country: 'US', code: 'TN' },
  { name: 'Texas', country: 'US', code: 'TX' },
  { name: 'Utah', country: 'US', code: 'UT' },
  { name: 'Vermont', country: 'US', code: 'VT' },
  { name: 'Virginia', country: 'US', code: 'VA' },
  { name: 'Washington', country: 'US', code: 'WA' },
  { name: 'West Virginia', country: 'US', code: 'WV' },
  { name: 'Wisconsin', country: 'US', code: 'WI' },
  { name: 'Wyoming', country: 'US', code: 'WY' },
  { name: 'Alberta', country: 'Canada', code: 'AB'},
  { name: 'British Columbia', country: 'Canada', code: 'BC'},
  { name: 'Manitoba', country: 'Canada', code: 'MB'},
  { name: 'New Brunswick', country: 'Canada', code: 'NB'},
  { name: 'Newfoundland and Labrador', country: 'Canada', code: 'NL'},
  { name: 'Northwest Territories', country: 'Canada', code: 'NT'},
  { name: 'Nova Scotia', country: 'Canada', code: 'NS'},
  { name: 'Nunavut', country: 'Canada', code: 'NU'},
  { name: 'Ontario', country: 'Canada', code: 'ON'},
  { name: 'Prince Edward Island', country: 'Canada', code: 'PE'},
  { name: 'Quebec', country: 'Canada', code: 'QC'},
  { name: 'Saskatchewan', country: 'Canada', code: 'SK'},
  { name: 'Yukon', country: 'Canada', code: 'YT'}
];
